services:
  - type: web
    name: orders-inventory-api
    runtime: python3
    buildCommand: pip install fastapi==0.95.2 uvicorn==0.20.0
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: sqlite:///./orders_inventory.db
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
    disk:
      name: orders-inventory-storage
      mountPath: /opt/render/project/data
      sizeGB: 1
  
  # Optional: Database service (PostgreSQL) for production
  # Uncomment if you want to use PostgreSQL instead of SQLite
  # - type: pserv
  #   name: orders-inventory-db
  #   runtime: postgresql
  #   ipAllowList: []
  #   databases:
  #     - name: orders_inventory
  #       user: orders_user
  #   envVars:
  #     - key: POSTGRES_DB
  #       value: orders_inventory
  #     - key: POSTGRES_USER
  #       value: orders_user
